name: Create release

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  release:
    name: Release notes
    runs-on: ubuntu-22.04
    steps:      
      - uses: actions/checkout@v3
      - name: Create release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          (gh release delete pr-${{ github.event.pull_request.id }} --yes --cleanup-tag || echo "ignore ^") &&\
          gh release create pr-${{ github.event.pull_request.id }} \
            --target="${{ github.event.pull_request.head.ref }}" \
            --generate-notes \
            --notes-start-tag=main \
            --latest=false