name: Create tag for commit
# We can only automatically generate release notes (in `create-release-note.yml) between
# the last commit and an existing tag. So we create a tag for each commit so we can see the difference.

on:
  push:
jobs:
  create-tag:
    name: Create tag for commit
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Create tag for commit
        run: |
          gh release create "commit-${{ github.sha }}" --latest=false
