name: Link to release note
# We want to have a link in the pr to the generated
# release note (created in `release-note_upsert-release-note.yml`)

on:
  pull_request:
    types: [opened]
jobs:
  release:
    name: Link to release note
    runs-on: ubuntu-22.04
    if: github.ref_name == 'develop'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Create release note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.pull_request.number }} --body "https://github.com/plug-and-pay/plug-and-pay/releases/tag/pr-${{ github.event.pull_request.number }}
          
          $(gh issue view ${{ github.event.pull_request.number }} --json body | jq -r '.body')"

# The extra white space above is intentional.
