name: Link to release note
# We want to have a link in every pr to the generated
# release note (created in `create-release-note.tml`)

on:
  pull_request:
    types: [opened]
jobs:
  release:
    name: Link to release note
    runs-on: ubuntu-22.04
    if: contains(fromJson('["refs/heads/develop", "refs/heads/release", "refs/heads/uat"]'), github.ref)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Create release note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.pull_request.number }} --body "https://github.com/plug-and-pay/plug-and-pay/releases/tag/pr-${{ github.event.pull_request.number }}
          
          $(gh issue view ${{ github.event.pull_request.number }} --json body | jq -r '.body')"

# The extra white space above is intentional.
