name: Upsert release note
# Generate a release note. For example: https://github.com/plug-and-pay/plug-and-pay/releases/tag/pr-4970

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  release:
    name: Upsert release note
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Debug
        run: echo "${{ github.ref_name }}"
      - name: Upsert release note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete pr-${{ github.event.pull_request.number }} --yes --cleanup-tag || true
          gh release create pr-${{ github.event.pull_request.number }} \
            --target="${{ github.event.pull_request.head.ref }}" \
            --generate-notes \
            --notes-start-tag=commit-${{ github.event.pull_request.base.sha }} \
            --latest=false
  